version: '2'
services:
  drupal:
    image: drupal:10-apache
    ports:
      - '80:80'
    volumes:
      - 'drupal_data:/var/www/html'
      - './web/modules:/var/www/html/modules'

volumes:
  drupal_data:
    driver: local
